/* eslint-disable @typescript-eslint/no-unused-vars */

const STORAGE_KEY = "infocutter.ruleStore";
const STORAGE_VERSION = 4;
const TEXT_BLOCK_STORAGE_KEY = "infocutter.textBlockStore";
const TEXT_BLOCK_STORAGE_VERSION = 1;
const STYLE_ELEMENT_ID = "infocutter-style-rules";
const SELECTOR_HIDDEN_ATTR = "data-infocutter-selector-hidden";
const TEXT_BLOCK_STYLE_ELEMENT_ID = "infocutter-text-block-rules";
const TEXT_BLOCK_HIDDEN_ATTR = "data-infocutter-text-block-hidden";
const PICKER_OVERLAY_ID = "infocutter-picker-overlay";
const PICKER_PREVIEW_STYLE_ID = "infocutter-preview-style";
const PICKER_PREVIEW_PANEL_ID = "infocutter-preview-panel";
const PICKER_STATUS_BADGE_ID = "infocutter-status-badge";
const PICKER_SESSION_PANEL_ID = "infocutter-session-panel";
const PICKER_SESSION_OVERLAY_ID = "infocutter-session-overlay";
const PICKER_FRAME_MESSAGE_TYPE = "infocutter/start-picker-in-frame";
const PICKER_FRAME_ACK_TYPE = "infocutter/start-picker-in-frame-ack";
const WATCH_STORAGE_KEY = "infocutter.watchStore";
const WATCH_STORAGE_VERSION = 1;
const WATCH_MASK_ATTR = "data-infocutter-watch-mask";
const WATCH_CHIP_ID = "infocutter-watch-chip";
const AI_RULE_STORAGE_KEY = "infocutter.aiRuleStore";
const AI_HIDDEN_ATTR = "data-infocutter-ai-hidden";
const AI_STYLE_ELEMENT_ID = "infocutter-ai-style-rules";
const AI_COLLECT_MAX_BLOCKS = 120;
const AI_COLLECT_MAX_TEXT_LENGTH = 200;

const messageTypes = InfocutterSelectorRules.infocutterMessageTypes;
