import { OCR_FIXTURE_ASSETS } from './ocr-fixture-assets.mjs';
import { createHash } from 'node:crypto';
import { open, readdir, readFile, lstat } from 'node:fs/promises';
import { resolve, relative } from 'node:path';
import { createReadStream } from 'node:fs';
import { brotliDecompressSync, gunzipSync } from 'node:zlib';

/** Extract the full generated credits from the exact shipped Windows DataPack. */
export function extractChromiumCredits(pak) {
  if (pak.length < 18 || pak.readUInt32LE(0) !== 5) throw new Error('Expected Chromium DataPack version 5');
  const count = pak.readUInt16LE(8);
  if (12 + (count + 1) * 6 > pak.length) throw new Error('Truncated DataPack entries');
  const matches = [];
  for (let index = 0; index < count; index++) {
    const entry = 12 + index * 6;
    const resourceId = pak.readUInt16LE(entry);
    const start = pak.readUInt32LE(entry + 2), end = pak.readUInt32LE(entry + 8);
    if (start > end || end > pak.length) throw new Error('Invalid DataPack offsets');
    const value = pak.subarray(start, end);
    let html;
    try {
      if (value.length >= 8 && value[0] === 0x1e && value[1] === 0x9b) {
        html = brotliDecompressSync(value.subarray(8));
        if (html.length !== value.readUIntLE(2, 6)) throw new Error('Credits decompression size differs');
      } else if (value[0] === 0x1f && value[1] === 0x8b) html = gunzipSync(value);
      else html = value;
    } catch (error) {
      if (error instanceof Error && error.message === 'Credits decompression size differs') throw error;
      continue;
    }
    const text = html.toString('utf8');
    if (text.includes('Generated by licenses.py') && /<html\b/i.test(text)) matches.push({ resourceId, html });
  }
  if (matches.length !== 1) throw new Error(`Expected exactly one complete generated credits resource, found ${matches.length}`);
  return matches[0];
}

export async function sha256(path) {
  const hash = createHash('sha256');
  for await (const bytes of createReadStream(path)) hash.update(bytes);
  return hash.digest('hex');
}
export async function inventory(root, options = {}) {
  const files = [];
  async function walk(path) {
    for (const entry of await readdir(path, { withFileTypes: true })) {
      const full = resolve(path, entry.name);
      const rel = relative(root, full).split('\\').join('/');
      if (entry.isSymbolicLink()) throw new Error(`Symlink forbidden in release: ${rel}`);
      const sourceModule = options.source === true && /^(src|test)\/output(?:\/|$)/.test(rel);
      if (/(^|\/)(\.env(?:\..*)?|\.git|\.dryforge)(\/|$)/i.test(rel) || (!sourceModule && /(^|\/)output(\/|$)/i.test(rel))) throw new Error(`Private path forbidden in release: ${rel}`);
      if (entry.isDirectory()) await walk(full);
      else if (entry.isFile()) files.push({ path: rel, bytes: (await lstat(full)).size, sha256: await sha256(full) });
      else throw new Error(`Unsupported release entry: ${rel}`);
    }
  }
  await walk(root);
  return files.sort((a, b) => a.path.localeCompare(b.path));
}
export async function assertPeX64(path) {
  const handle = await open(path, 'r');
  try {
    const header = Buffer.alloc(64);
    if ((await handle.read(header, 0, 64, 0)).bytesRead !== 64 || header.toString('ascii', 0, 2) !== 'MZ') throw new Error(`Not a PE executable: ${path}`);
    const offset = header.readUInt32LE(0x3c);
    const pe = Buffer.alloc(26);
    if ((await handle.read(pe, 0, 26, offset)).bytesRead !== 26 || pe.readUInt32LE(0) !== 0x00004550 || pe.readUInt16LE(4) !== 0x8664 || pe.readUInt16LE(24) !== 0x20b) throw new Error(`Expected Windows x64 PE32+: ${path}`);
  } finally { await handle.close(); }
}
/** Checked-in fixture allowlist, actual bytes and independent source manifest are mandatory. */
export async function verifyFixtureAssets(directory) {
  const names=(await readdir(directory)).sort();
  if(JSON.stringify(names)!==JSON.stringify([...OCR_FIXTURE_ASSETS].sort()))throw new Error('Unexpected or missing OCR fixture asset');
  const manifest=JSON.parse(await readFile(resolve(directory,'manifest.json'),'utf8'));
  for(const item of manifest){
    if(!OCR_FIXTURE_ASSETS.includes(item.file)||!/^[a-f0-9]{64}$/.test(item.sha256)||!Number.isInteger(item.byteLength))throw new Error('Invalid OCR fixture manifest');
    const stat=await lstat(resolve(directory,item.file));if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==item.byteLength||await sha256(resolve(directory,item.file))!==item.sha256)throw new Error('OCR fixture bytes differ from independent manifest');
  }
  for(const name of OCR_FIXTURE_ASSETS){const stat=await lstat(resolve(directory,name));if(!stat.isFile()||stat.isSymbolicLink())throw new Error('Invalid OCR fixture asset');}
  return OCR_FIXTURE_ASSETS;
}
export async function verifyPackage(root, manifest) {
  const files = await inventory(root);
  const names = new Set(files.map(file => file.path));
  const required = ['Inspektor.exe', 'LICENSE', 'LICENSES.chromium.html', 'resources/runtime/node.exe', 'resources/runtime/LICENSE',
    'resources/browser/chrome-win64/chrome.exe', 'resources/browser/chrome-win64/chrome.dll', 'resources/browser/LICENSE', 'resources/browser/LICENSES.chromium.html',
    'resources/app/dist/desktop.mjs', 'resources/app/dist/self-test.mjs', 'resources/app/dist/self-test.mjs.map', 'resources/app/dist/public/index.html', 'resources/app/dist/public/web.js', 'resources/app/dist/public/web.css',
    'resources/app/dist/resources/tokenizer.json', 'resources/app/dist/resources/LICENSE', 'resources/app/dist/resources/provenance.json',
    'resources/app/node_modules/playwright/package.json', 'resources/app/node_modules/playwright-core/package.json',
    'resources/app/node_modules/dotenv/package.json', 'resources/app/node_modules/@huggingface/tokenizers/package.json', 'resources/app/THIRD-PARTY-NOTICES.json'];
  for (const name of OCR_FIXTURE_ASSETS) required.push('resources/app/dist/ocr-assets/'+name);
  for (const name of required) if (!names.has(name)) throw new Error(`Missing release requirement: ${name}`);
  await verifyFixtureAssets(resolve(root,'resources/app/dist/ocr-assets'));
  for (const file of files.filter(file => /\.(exe|dll)$/i.test(file.path))) await assertPeX64(resolve(root, file.path));
  const packageJson = JSON.parse(await readFile(resolve(root, 'resources/app/package.json'), 'utf8'));
  if (packageJson.main !== 'dist/desktop.mjs' || packageJson.devDependencies) throw new Error('Invalid production entry/dependencies');
  for (const [name, version] of Object.entries(manifest.versions.production)) {
    const dependency = JSON.parse(await readFile(resolve(root, 'resources/app/node_modules', name, 'package.json'), 'utf8'));
    if (dependency.version !== version) throw new Error(`Dependency version mismatch: ${name}`);
  }
  if (manifest.files && JSON.stringify(files) !== JSON.stringify(manifest.files)) throw new Error('Release bytes do not match manifest');
  return files;
}
